More stuff

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -25,27 +25,43 @@ jobs:
           - 'nightly'
         os:
           - ubuntu-latest
+          - windows-latest
           - macos-12 # Intel
           - macos-13 # Intel
           - macos-14 # Apple Silicon
-          - windows-latest
-        arch:
-          - x64
-          - x86
-          - aarch64
+        julia-word-size:
+          - '32'
+          - '64'
         exclude:
-          - os: macOS-latest-xlarge
-            arch: x86
-          - os: ubuntu-latest
-            arch: aarch64
-          - os: windows-latest
-            arch: aarch64
+          - os: macos-12
+            julia-word-size: '32'
+          - os: macos-13
+            julia-word-size: '32'
+          - os: macos-14
+            julia-word-size: '32'
     steps:
       - uses: actions/checkout@v4
+      - name: Determine the value of JULIA_ARCH
+        id: determine-julia-arch
+        shell: bash
+        env:
+          JULIA_WORD_SIZE: ${{ matrix.julia-word-size }}
+        run: |
+          echo "RUNNER_ARCH is: ${RUNNER_ARCH:?}"
+          if [[ "${JULIA_WORD_SIZE:?}" == "32" ]]; then
+            echo "julia-arch=x86" >> "${GITHUB_OUTPUT:?}"
+          elif [[ "$JULIA_WORD_SIZE" == "64" ]]; then
+            echo 'a is greater than b'
+            echo "julia-arch=${RUNNER_ARCH:?}" >> "${GITHUB_OUTPUT:?}"
+          else
+            echo "Invalid value for JULIA_WORD_SIZE: ${JULIA_WORD_SIZE:?}"
+            exit 1
+          fi
+      - run: JULIA_ARCH is "${{ steps.determine-julia-arch.outputs.julia-arch }}"
       - uses: julia-actions/setup-julia@v1
         with:
           version: ${{ matrix.version }}
-          arch: ${{ runner.arch }}
+          arch: ${{ steps.determine-julia-arch.outputs.julia-arch }}
       - uses: actions/cache@v4
         env:
           cache-name: cache-artifacts
